logging:
  level:
    org.springframework: error
    org.springframework.security: debug



spring:
  main:
    allow-bean-definition-overriding: true
  data:
    cassandra:
      keyspace-name: cassandra_oauth_1
      contact-points: ${CASSANDRA_HOST:localhost}
      port: 9042
      schema-action: recreate
server:
  port: 8080

cassandra:
  basepackages: com.herokuapp.samkaz

